services:
  # Твоя база
  db:
    image: postgres:15
    container_name: contest_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: contest_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Твой редис
  redis:
    image: redis:7-alpine
    container_name: contest_redis
    ports:
      - "6379:6379"

  # ТВОЙ ВОРКЕР (Блок обновлен для браузера)
  worker_a1:
    build: 
      context: .
      dockerfile: ./function1/Dockerfile
    container_name: worker_a1
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - db
    volumes:
      # Мы пробрасываем ГЛАВНУЮ папку внутрь. 
      # Внутри докера она будет называться /var/lib/browser_sessions
      - ./sessions_storage:/var/lib/browser_sessions



    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:password123@db:5432/contest_monitor
        # ТВОЙ БОТ (Интерфейс оператора)
  service_bot:
    build: 
      context: .
      dockerfile: ./function1/Dockerfile # Используем тот же докерфайл, там есть все либы
    container_name: service_bot
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:password123@db:5432/contest_monitor
      - BOT_TOKEN=8410272638:AAEwO-OMhqMSj1GNKdsi5fnJwgPZCi6Qzco
    # Команда запуска именно для бота:
    command: python -u service_bot/main.py


# --- СЕКЦИЯ ТОМОВ (В самом низу файла) ---
volumes:
  postgres_data:
  # --- ДОБАВЬ ЭТУ СТРОКУ ТУТ ---
  browser_data: 
