services:
  # Твоя база
  db:
    image: postgres:15
    container_name: contest_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: contest_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Твой редис
  redis:
    image: redis:7-alpine
    container_name: contest_redis
    ports:
      - "6379:6379"

  # ТВОЙ ВОРКЕР (Блок должен быть СДВИНУТ вправо, как и db/redis)
  worker_a1:
    build: 
      context: .
      dockerfile: ./function1/Dockerfile
    container_name: worker_a1
    restart: always
    # УДАЛИ network_mode: "host"
    # ДОБАВИ DNS для интернета:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - db
    environment:
      # ВЕРНИ 'db', чтобы воркер видел контейнер базы
      - DATABASE_URL=postgresql+asyncpg://admin:password123@db:5432/contest_monitor

volumes:
  postgres_data:
